lexer grammar DockerfileLexer;

tokens {
    NONE,
    INVALID_DIRECTIVE,
    STRING_START,
    STRING_TEXT,
    STRING_END,
    JSON_STRING_START,
    JSON_STRING_TEXT,
    JSON_STRING_SPACE,
    JSON_STRING_ESCAPE,
    JSON_STRING_END,
    EQUALS,
    ESCAPE,
    BUILDER_FLAG_START,
    BUILDER_FLAG_TEXT
}

// DEFAULT_MODE is the initial parser-directive preamble. Dockerfiles use
// backslash escapes unless a valid top-of-file directive selects backtick.

BACKTICK_ESCAPE_DIRECTIVE
    : ESCAPE_DIRECTIVE_PREFIX '`' [ \t]* LINE_END
      -> mode(BACKTICK_PREAMBLE)
    ;
BACKSLASH_ESCAPE_DIRECTIVE
    : ESCAPE_DIRECTIVE_PREFIX '\\' [ \t]* LINE_END
    ;
SYNTAX_DIRECTIVE
    : SYNTAX_DIRECTIVE_PREFIX DIRECTIVE_VALUE LINE_END
    ;
CHECK_DIRECTIVE
    : CHECK_DIRECTIVE_PREFIX DIRECTIVE_VALUE LINE_END
    ;
INVALID_ESCAPE_DIRECTIVE
    : (
        ESCAPE_DIRECTIVE_PREFIX DIRECTIVE_VALUE
        | ESCAPE_DIRECTIVE_HEAD [ \t]+
      ) LINE_END
      -> type(INVALID_DIRECTIVE), mode(SLASH_BODY)
    ;

FROM: FROM_WORD -> mode(SLASH_ARG_PREAMBLE);
RUN: RUN_WORD -> mode(SLASH_ARG_PREAMBLE);
CMD: CMD_WORD -> mode(SLASH_ARG_PREAMBLE);
LABEL: LABEL_WORD -> mode(SLASH_ARG_PREAMBLE);
EXPOSE: EXPOSE_WORD -> mode(SLASH_ARG_PREAMBLE);
ENV: ENV_WORD -> mode(SLASH_ARG_PREAMBLE);
ADD: ADD_WORD -> mode(SLASH_ARG_PREAMBLE);
COPY: COPY_WORD -> mode(SLASH_ARG_PREAMBLE);
ENTRYPOINT: ENTRYPOINT_WORD -> mode(SLASH_ARG_PREAMBLE);
VOLUME: VOLUME_WORD -> mode(SLASH_ARG_PREAMBLE);
USER: USER_WORD -> mode(SLASH_ARG_PREAMBLE);
WORKDIR: WORKDIR_WORD -> mode(SLASH_ARG_PREAMBLE);
ARG: ARG_WORD -> mode(SLASH_ARG_PREAMBLE);
ONBUILD: ONBUILD_WORD -> mode(SLASH_BODY);
STOPSIGNAL: STOPSIGNAL_WORD -> mode(SLASH_ARG_PREAMBLE);
HEALTHCHECK: HEALTHCHECK_WORD -> mode(SLASH_ARG_PREAMBLE);
SHELL: SHELL_WORD -> mode(SLASH_ARG_PREAMBLE);

COMMENT: [ \t]* '#' ~[\r\n]* -> mode(SLASH_BODY), skip;
NL: NEWLINE+ -> mode(SLASH_BODY);
WS: [ \t]+ -> skip;

fragment ESCAPE_DIRECTIVE_PREFIX
    : ESCAPE_DIRECTIVE_HEAD [ \t]*
    ;
fragment ESCAPE_DIRECTIVE_HEAD
    : [ \t]* '#' [ \t]* ESCAPE_WORD [ \t]* '='
    ;
fragment SYNTAX_DIRECTIVE_PREFIX
    : [ \t]* '#' [ \t]* SYNTAX_WORD [ \t]* '=' [ \t]*
    ;
fragment CHECK_DIRECTIVE_PREFIX
    : [ \t]* '#' [ \t]* CHECK_WORD [ \t]* '=' [ \t]*
    ;
fragment DIRECTIVE_VALUE: ~[ \t\r\n] ~[\r\n]*;
fragment LINE_END: NEWLINE | EOF;
fragment NEWLINE: '\r'? '\n' | '\r';
fragment JSON_ESCAPE_SEQUENCE
    : '\\' (["\\/bfnrt] | 'u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT)
    ;
fragment HEX_DIGIT: [0-9a-fA-F];
fragment EMPTY_BUILDER_FLAG_QUOTES: ('""' | '\'\'')+;
fragment CONTINUATION_IGNORED_LINE
    : [ \t]* ('#' ~[\r\n]*)? NEWLINE
    ;

fragment ESCAPE_WORD: [eE][sS][cC][aA][pP][eE];
fragment SYNTAX_WORD: [sS][yY][nN][tT][aA][xX];
fragment CHECK_WORD: [cC][hH][eE][cC][kK];

fragment FROM_WORD: [fF][rR][oO][mM];
fragment RUN_WORD: [rR][uU][nN];
fragment CMD_WORD: [cC][mM][dD];
fragment LABEL_WORD: [lL][aA][bB][eE][lL];
fragment EXPOSE_WORD: [eE][xX][pP][oO][sS][eE];
fragment ENV_WORD: [eE][nN][vV];
fragment ADD_WORD: [aA][dD][dD];
fragment COPY_WORD: [cC][oO][pP][yY];
fragment ENTRYPOINT_WORD: [eE][nN][tT][rR][yY][pP][oO][iI][nN][tT];
fragment VOLUME_WORD: [vV][oO][lL][uU][mM][eE];
fragment USER_WORD: [uU][sS][eE][rR];
fragment WORKDIR_WORD: [wW][oO][rR][kK][dD][iI][rR];
fragment ARG_WORD: [aA][rR][gG];
fragment ONBUILD_WORD: [oO][nN][bB][uU][iI][lL][dD];
fragment STOPSIGNAL_WORD: [sS][tT][oO][pP][sS][iI][gG][nN][aA][lL];
fragment HEALTHCHECK_WORD: [hH][eE][aA][lL][tT][hH][cC][hH][eE][cC][kK];
fragment SHELL_WORD: [sS][hH][eE][lL][lL];

// Backtick remains selected while the parser-directive preamble is open.
mode BACKTICK_PREAMBLE;

BACKTICK_PREAMBLE_BACKTICK_ESCAPE
    : ESCAPE_DIRECTIVE_PREFIX '`' [ \t]* LINE_END
      -> type(BACKTICK_ESCAPE_DIRECTIVE)
    ;
BACKTICK_PREAMBLE_BACKSLASH_ESCAPE
    : ESCAPE_DIRECTIVE_PREFIX '\\' [ \t]* LINE_END
      -> type(BACKSLASH_ESCAPE_DIRECTIVE), mode(DEFAULT_MODE)
    ;
BACKTICK_PREAMBLE_SYNTAX
    : SYNTAX_DIRECTIVE_PREFIX DIRECTIVE_VALUE LINE_END
      -> type(SYNTAX_DIRECTIVE)
    ;
BACKTICK_PREAMBLE_CHECK
    : CHECK_DIRECTIVE_PREFIX DIRECTIVE_VALUE LINE_END
      -> type(CHECK_DIRECTIVE)
    ;
BACKTICK_PREAMBLE_INVALID_ESCAPE
    : (
        ESCAPE_DIRECTIVE_PREFIX DIRECTIVE_VALUE
        | ESCAPE_DIRECTIVE_HEAD [ \t]+
      ) LINE_END
      -> type(INVALID_DIRECTIVE), mode(BACKTICK_BODY)
    ;

BACKTICK_PREAMBLE_FROM
    : FROM_WORD -> type(FROM), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_RUN
    : RUN_WORD -> type(RUN), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_CMD
    : CMD_WORD -> type(CMD), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_LABEL
    : LABEL_WORD -> type(LABEL), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_EXPOSE
    : EXPOSE_WORD -> type(EXPOSE), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_ENV
    : ENV_WORD -> type(ENV), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_ADD
    : ADD_WORD -> type(ADD), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_COPY
    : COPY_WORD -> type(COPY), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_ENTRYPOINT
    : ENTRYPOINT_WORD -> type(ENTRYPOINT), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_VOLUME
    : VOLUME_WORD -> type(VOLUME), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_USER
    : USER_WORD -> type(USER), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_WORKDIR
    : WORKDIR_WORD -> type(WORKDIR), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_ARG
    : ARG_WORD -> type(ARG), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_ONBUILD
    : ONBUILD_WORD -> type(ONBUILD), mode(BACKTICK_BODY)
    ;
BACKTICK_PREAMBLE_STOPSIGNAL
    : STOPSIGNAL_WORD -> type(STOPSIGNAL), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_HEALTHCHECK
    : HEALTHCHECK_WORD -> type(HEALTHCHECK), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_PREAMBLE_SHELL
    : SHELL_WORD -> type(SHELL), mode(BACKTICK_ARG_PREAMBLE)
    ;

BACKTICK_PREAMBLE_COMMENT
    : [ \t]* '#' ~[\r\n]* -> mode(BACKTICK_BODY), skip
    ;
BACKTICK_PREAMBLE_NL: NEWLINE+ -> type(NL), mode(BACKTICK_BODY);
BACKTICK_PREAMBLE_WS: [ \t]+ -> skip;

// Top-level instruction modes after the parser-directive preamble closes.
mode SLASH_BODY;

SLASH_FROM: FROM_WORD -> type(FROM), mode(SLASH_ARG_PREAMBLE);
SLASH_RUN: RUN_WORD -> type(RUN), mode(SLASH_ARG_PREAMBLE);
SLASH_CMD: CMD_WORD -> type(CMD), mode(SLASH_ARG_PREAMBLE);
SLASH_LABEL: LABEL_WORD -> type(LABEL), mode(SLASH_ARG_PREAMBLE);
SLASH_EXPOSE: EXPOSE_WORD -> type(EXPOSE), mode(SLASH_ARG_PREAMBLE);
SLASH_ENV: ENV_WORD -> type(ENV), mode(SLASH_ARG_PREAMBLE);
SLASH_ADD: ADD_WORD -> type(ADD), mode(SLASH_ARG_PREAMBLE);
SLASH_COPY: COPY_WORD -> type(COPY), mode(SLASH_ARG_PREAMBLE);
SLASH_ENTRYPOINT
    : ENTRYPOINT_WORD -> type(ENTRYPOINT), mode(SLASH_ARG_PREAMBLE)
    ;
SLASH_VOLUME: VOLUME_WORD -> type(VOLUME), mode(SLASH_ARG_PREAMBLE);
SLASH_USER: USER_WORD -> type(USER), mode(SLASH_ARG_PREAMBLE);
SLASH_WORKDIR: WORKDIR_WORD -> type(WORKDIR), mode(SLASH_ARG_PREAMBLE);
SLASH_ARG: ARG_WORD -> type(ARG), mode(SLASH_ARG_PREAMBLE);
SLASH_ONBUILD: ONBUILD_WORD -> type(ONBUILD);
SLASH_STOPSIGNAL
    : STOPSIGNAL_WORD -> type(STOPSIGNAL), mode(SLASH_ARG_PREAMBLE)
    ;
SLASH_HEALTHCHECK
    : HEALTHCHECK_WORD -> type(HEALTHCHECK), mode(SLASH_ARG_PREAMBLE)
    ;
SLASH_SHELL: SHELL_WORD -> type(SHELL), mode(SLASH_ARG_PREAMBLE);

SLASH_COMMENT: [ \t]* '#' ~[\r\n]* -> skip;
SLASH_NL: NEWLINE+ -> type(NL);
SLASH_WS: [ \t]+ -> skip;

mode BACKTICK_BODY;

BACKTICK_FROM: FROM_WORD -> type(FROM), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_RUN: RUN_WORD -> type(RUN), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_CMD: CMD_WORD -> type(CMD), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_LABEL: LABEL_WORD -> type(LABEL), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_EXPOSE: EXPOSE_WORD -> type(EXPOSE), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_ENV: ENV_WORD -> type(ENV), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_ADD: ADD_WORD -> type(ADD), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_COPY: COPY_WORD -> type(COPY), mode(BACKTICK_ARG_PREAMBLE);
BACKTICK_ENTRYPOINT
    : ENTRYPOINT_WORD -> type(ENTRYPOINT), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_VOLUME
    : VOLUME_WORD -> type(VOLUME), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_USER
    : USER_WORD -> type(USER), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_WORKDIR
    : WORKDIR_WORD -> type(WORKDIR), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_ARG
    : ARG_WORD -> type(ARG), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_ONBUILD: ONBUILD_WORD -> type(ONBUILD);
BACKTICK_STOPSIGNAL
    : STOPSIGNAL_WORD -> type(STOPSIGNAL), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_HEALTHCHECK
    : HEALTHCHECK_WORD -> type(HEALTHCHECK), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_SHELL
    : SHELL_WORD -> type(SHELL), mode(BACKTICK_ARG_PREAMBLE)
    ;

BACKTICK_COMMENT: [ \t]* '#' ~[\r\n]* -> skip;
BACKTICK_NL: NEWLINE+ -> type(NL);
BACKTICK_WS: [ \t]+ -> skip;

// Builder flags are decoded only while the instruction argument preamble is
// open. The first ordinary argument or a bare "--" switches to raw arguments.
mode SLASH_ARG_PREAMBLE;

SLASH_PREAMBLE_LINE_CONT
    : '\\' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
SLASH_PREAMBLE_NL
    : [ \t]* NEWLINE -> type(NL), mode(SLASH_BODY)
    ;
SLASH_PREAMBLE_UNCLOSED_QUOTE_TERMINATOR_NL
    : '--' EMPTY_BUILDER_FLAG_QUOTES? ('"' | '\'') NEWLINE
      -> type(NL), mode(SLASH_BODY)
    ;
SLASH_PREAMBLE_QUOTED_FLAG_TERMINATOR_NL
    : '--' EMPTY_BUILDER_FLAG_QUOTES [ \t]* NEWLINE
      -> type(NL), mode(SLASH_BODY)
    ;
SLASH_PREAMBLE_QUOTED_FLAG_TERMINATOR
    : '--' EMPTY_BUILDER_FLAG_QUOTES [ \t]+
      -> type(BUILDER_FLAG_TERMINATOR), mode(SLASH_ARGS)
    ;
SLASH_PREAMBLE_FLAG_TERMINATOR_NL
    : '--' [ \t]* NEWLINE -> type(NL), mode(SLASH_BODY)
    ;
SLASH_PREAMBLE_FLAG_TERMINATOR
    : '--' [ \t]+ -> type(BUILDER_FLAG_TERMINATOR), mode(SLASH_ARGS)
    ;
SLASH_PREAMBLE_FLAG_START
    : '--' -> type(BUILDER_FLAG_START), mode(SLASH_BUILDER_FLAG)
    ;
SLASH_PREAMBLE_WS: [ \t] -> type(ARG_WS);
SLASH_PREAMBLE_LBRACKET: '[' -> type(LBRACKET), mode(SLASH_ARGS);
SLASH_PREAMBLE_RBRACKET: ']' -> type(RBRACKET), mode(SLASH_ARGS);
SLASH_PREAMBLE_COMMA: ',' -> type(COMMA), mode(SLASH_ARGS);
SLASH_PREAMBLE_DOUBLE_STRING_START
    : '"' -> type(JSON_STRING_START), mode(SLASH_DOUBLE_QUOTE)
    ;
SLASH_PREAMBLE_SINGLE_STRING_START
    : '\'' -> type(STRING_START), mode(SLASH_SINGLE_QUOTE)
    ;
SLASH_PREAMBLE_NONE
    : [nN][oO][nN][eE] -> type(NONE), mode(SLASH_ARGS)
    ;
SLASH_PREAMBLE_CMD: [cC][mM][dD] -> type(CMD), mode(SLASH_ARGS);
SLASH_PREAMBLE_EQUALS: '=' -> type(EQUALS), mode(SLASH_ARGS);
SLASH_PREAMBLE_ESCAPED_CHAR
    : '\\' ~[\r\n \t] -> type(ARG_TEXT), mode(SLASH_ARGS)
    ;
SLASH_PREAMBLE_TEXT
    : ~[-\r\n \t[\],="'#\\]+ -> type(ARG_TEXT), mode(SLASH_ARGS)
    ;
SLASH_PREAMBLE_HYPHEN: '-' -> type(ARG_TEXT), mode(SLASH_ARGS);
SLASH_PREAMBLE_HASH: '#' -> type(ARG_TEXT), mode(SLASH_ARGS);
SLASH_PREAMBLE_BACKSLASH: '\\' -> type(ESCAPE), mode(SLASH_ARGS);
SLASH_PREAMBLE_OTHER: . -> type(ARG_TEXT), mode(SLASH_ARGS);

mode BACKTICK_ARG_PREAMBLE;

BACKTICK_ARG_PREAMBLE_LINE_CONT
    : '`' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
BACKTICK_ARG_PREAMBLE_NL
    : [ \t]* NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_ARG_PREAMBLE_UNCLOSED_QUOTE_TERMINATOR_NL
    : '--' EMPTY_BUILDER_FLAG_QUOTES? ('"' | '\'') NEWLINE
      -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_ARG_PREAMBLE_QUOTED_FLAG_TERMINATOR_NL
    : '--' EMPTY_BUILDER_FLAG_QUOTES [ \t]* NEWLINE
      -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_ARG_PREAMBLE_QUOTED_FLAG_TERMINATOR
    : '--' EMPTY_BUILDER_FLAG_QUOTES [ \t]+
      -> type(BUILDER_FLAG_TERMINATOR), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_FLAG_TERMINATOR_NL
    : '--' [ \t]* NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_ARG_PREAMBLE_FLAG_TERMINATOR
    : '--' [ \t]+ -> type(BUILDER_FLAG_TERMINATOR), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_FLAG_START
    : '--' -> type(BUILDER_FLAG_START), mode(BACKTICK_BUILDER_FLAG)
    ;
BACKTICK_ARG_PREAMBLE_WS: [ \t] -> type(ARG_WS);
BACKTICK_ARG_PREAMBLE_LBRACKET
    : '[' -> type(LBRACKET), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_RBRACKET
    : ']' -> type(RBRACKET), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_COMMA
    : ',' -> type(COMMA), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_DOUBLE_STRING_START
    : '"' -> type(JSON_STRING_START), mode(BACKTICK_DOUBLE_QUOTE)
    ;
BACKTICK_ARG_PREAMBLE_SINGLE_STRING_START
    : '\'' -> type(STRING_START), mode(BACKTICK_SINGLE_QUOTE)
    ;
BACKTICK_ARG_PREAMBLE_NONE
    : [nN][oO][nN][eE] -> type(NONE), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_CMD
    : [cC][mM][dD] -> type(CMD), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_EQUALS: '=' -> type(EQUALS), mode(BACKTICK_ARGS);
BACKTICK_ARG_PREAMBLE_ESCAPED_CHAR
    : '`' ~[\r\n \t] -> type(ARG_TEXT), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_TEXT
    : ~[-\r\n \t[\],="'#`]+ -> type(ARG_TEXT), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_HYPHEN
    : '-' -> type(ARG_TEXT), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_HASH
    : '#' -> type(ARG_TEXT), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_BACKTICK
    : '`' -> type(ESCAPE), mode(BACKTICK_ARGS)
    ;
BACKTICK_ARG_PREAMBLE_OTHER: . -> type(ARG_TEXT), mode(BACKTICK_ARGS);

// Argument modes differ only where the selected escape character matters.
mode SLASH_ARGS;

ARG_LINE_CONT
    : '\\' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
ARG_NL: [ \t]* NEWLINE -> type(NL), mode(SLASH_BODY);

BUILDER_FLAG: '--' SLASH_BUILDER_FLAG_PART+;
BUILDER_FLAG_TERMINATOR: '--';

fragment SLASH_BUILDER_FLAG_PART
    : ~[\r\n \t"'\\]
    | SLASH_BUILDER_FLAG_ESCAPE
    | '"' ( ~["\\\r\n] | SLASH_BUILDER_FLAG_ESCAPE )* '"'
    | '\'' ( ~['\\\r\n] | SLASH_BUILDER_FLAG_ESCAPE )* '\''
    ;
fragment SLASH_BUILDER_FLAG_ESCAPE
    : '\\' (
        [ \t]* NEWLINE CONTINUATION_IGNORED_LINE*
        | .
      )?
    ;

LBRACKET: '[';
RBRACKET: ']';
COMMA: ',';
SLASH_DOUBLE_STRING_START
    : '"' -> type(JSON_STRING_START), mode(SLASH_DOUBLE_QUOTE)
    ;
SLASH_SINGLE_STRING_START
    : '\'' -> type(STRING_START), mode(SLASH_SINGLE_QUOTE)
    ;
ARG_NONE: [nN][oO][nN][eE] -> type(NONE);
ARG_CMD: [cC][mM][dD] -> type(CMD);
ARG_EQUALS: '=' -> type(EQUALS);
ARG_ESCAPED_CHAR: '\\' ~[\r\n \t] -> type(ARG_TEXT);
ARG_TEXT: ~[\r\n \t[\],="'#\\]+;
// Keep the character after ESCAPE separate from any following separator.
ARG_WS: [ \t];
ARG_HASH: '#' -> type(ARG_TEXT);
ARG_BACKSLASH: '\\' -> type(ESCAPE);
ANY_OTHER: . -> type(ARG_TEXT);

mode BACKTICK_ARGS;

BACKTICK_ARG_LINE_CONT
    : '`' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
BACKTICK_ARG_NL: [ \t]* NEWLINE -> type(NL), mode(BACKTICK_BODY);

BACKTICK_BUILDER_FLAG
    : '--' BACKTICK_BUILDER_FLAG_PART+ -> type(BUILDER_FLAG)
    ;
BACKTICK_BUILDER_FLAG_TERMINATOR: '--' -> type(BUILDER_FLAG_TERMINATOR);

fragment BACKTICK_BUILDER_FLAG_PART
    : ~[\r\n \t"'`]
    | BACKTICK_BUILDER_FLAG_ESCAPE
    | '"' ( ~["`\r\n] | BACKTICK_BUILDER_FLAG_ESCAPE )* '"'
    | '\'' ( ~['`\r\n] | BACKTICK_BUILDER_FLAG_ESCAPE )* '\''
    ;
fragment BACKTICK_BUILDER_FLAG_ESCAPE
    : '`' (
        [ \t]* NEWLINE CONTINUATION_IGNORED_LINE*
        | .
      )?
    ;

BACKTICK_LBRACKET: '[' -> type(LBRACKET);
BACKTICK_RBRACKET: ']' -> type(RBRACKET);
BACKTICK_COMMA: ',' -> type(COMMA);
BACKTICK_DOUBLE_STRING_START
    : '"' -> type(JSON_STRING_START), mode(BACKTICK_DOUBLE_QUOTE)
    ;
BACKTICK_SINGLE_STRING_START
    : '\'' -> type(STRING_START), mode(BACKTICK_SINGLE_QUOTE)
    ;
BACKTICK_ARG_NONE: [nN][oO][nN][eE] -> type(NONE);
BACKTICK_ARG_CMD: [cC][mM][dD] -> type(CMD);
BACKTICK_ARG_EQUALS: '=' -> type(EQUALS);
BACKTICK_ARG_ESCAPED_CHAR: '`' ~[\r\n \t] -> type(ARG_TEXT);
BACKTICK_ARG_TEXT: ~[\r\n \t[\],="'#`]+ -> type(ARG_TEXT);
BACKTICK_ARG_WS: [ \t] -> type(ARG_WS);
BACKTICK_ARG_HASH: '#' -> type(ARG_TEXT);
BACKTICK_ARG_BACKTICK: '`' -> type(ESCAPE);
BACKTICK_ANY_OTHER: . -> type(ARG_TEXT);

mode SLASH_BUILDER_FLAG;

SLASH_FLAG_DOUBLE_QUOTE
    : '"' -> skip, mode(SLASH_BUILDER_FLAG_DOUBLE_QUOTE)
    ;
SLASH_FLAG_SINGLE_QUOTE
    : '\'' -> skip, mode(SLASH_BUILDER_FLAG_SINGLE_QUOTE)
    ;
SLASH_FLAG_ESCAPE
    : '\\' -> skip, pushMode(SLASH_BUILDER_FLAG_ESCAPE)
    ;
SLASH_FLAG_WS
    : [ \t] -> type(ARG_WS), mode(SLASH_ARG_PREAMBLE)
    ;
SLASH_FLAG_NL: NEWLINE -> type(NL), mode(SLASH_BODY);
SLASH_FLAG_TEXT
    : ~[\r\n \t"'\\]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode SLASH_BUILDER_FLAG_DOUBLE_QUOTE;

SLASH_FLAG_DOUBLE_QUOTE_END: '"' -> skip, mode(SLASH_BUILDER_FLAG);
SLASH_FLAG_DOUBLE_QUOTE_ESCAPE
    : '\\' -> skip, pushMode(SLASH_BUILDER_FLAG_ESCAPE)
    ;
SLASH_FLAG_DOUBLE_QUOTE_NL: NEWLINE -> type(NL), mode(SLASH_BODY);
SLASH_FLAG_DOUBLE_QUOTE_TEXT
    : ~["\\\r\n]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode SLASH_BUILDER_FLAG_SINGLE_QUOTE;

SLASH_FLAG_SINGLE_QUOTE_END: '\'' -> skip, mode(SLASH_BUILDER_FLAG);
SLASH_FLAG_SINGLE_QUOTE_ESCAPE
    : '\\' -> skip, pushMode(SLASH_BUILDER_FLAG_ESCAPE)
    ;
SLASH_FLAG_SINGLE_QUOTE_NL: NEWLINE -> type(NL), mode(SLASH_BODY);
SLASH_FLAG_SINGLE_QUOTE_TEXT
    : ~['\\\r\n]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode SLASH_BUILDER_FLAG_ESCAPE;

SLASH_FLAG_ESCAPED_CONTINUATION
    : [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip, popMode
    ;
SLASH_FLAG_ESCAPED_CHAR: . -> type(BUILDER_FLAG_TEXT), popMode;

mode BACKTICK_BUILDER_FLAG;

BACKTICK_FLAG_DOUBLE_QUOTE
    : '"' -> skip, mode(BACKTICK_BUILDER_FLAG_DOUBLE_QUOTE)
    ;
BACKTICK_FLAG_SINGLE_QUOTE
    : '\'' -> skip, mode(BACKTICK_BUILDER_FLAG_SINGLE_QUOTE)
    ;
BACKTICK_FLAG_ESCAPE
    : '`' -> skip, pushMode(BACKTICK_BUILDER_FLAG_ESCAPE)
    ;
BACKTICK_FLAG_WS
    : [ \t] -> type(ARG_WS), mode(BACKTICK_ARG_PREAMBLE)
    ;
BACKTICK_FLAG_NL: NEWLINE -> type(NL), mode(BACKTICK_BODY);
BACKTICK_FLAG_TEXT
    : ~[\r\n \t"'`]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode BACKTICK_BUILDER_FLAG_DOUBLE_QUOTE;

BACKTICK_FLAG_DOUBLE_QUOTE_END
    : '"' -> skip, mode(BACKTICK_BUILDER_FLAG)
    ;
BACKTICK_FLAG_DOUBLE_QUOTE_ESCAPE
    : '`' -> skip, pushMode(BACKTICK_BUILDER_FLAG_ESCAPE)
    ;
BACKTICK_FLAG_DOUBLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_FLAG_DOUBLE_QUOTE_TEXT
    : ~["`\r\n]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode BACKTICK_BUILDER_FLAG_SINGLE_QUOTE;

BACKTICK_FLAG_SINGLE_QUOTE_END
    : '\'' -> skip, mode(BACKTICK_BUILDER_FLAG)
    ;
BACKTICK_FLAG_SINGLE_QUOTE_ESCAPE
    : '`' -> skip, pushMode(BACKTICK_BUILDER_FLAG_ESCAPE)
    ;
BACKTICK_FLAG_SINGLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_FLAG_SINGLE_QUOTE_TEXT
    : ~['`\r\n]+ -> type(BUILDER_FLAG_TEXT)
    ;

mode BACKTICK_BUILDER_FLAG_ESCAPE;

BACKTICK_FLAG_ESCAPED_CONTINUATION
    : [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip, popMode
    ;
BACKTICK_FLAG_ESCAPED_CHAR: . -> type(BUILDER_FLAG_TEXT), popMode;

mode SLASH_DOUBLE_QUOTE;

// JSON-valid pieces stay distinct; generic parser rules also accept the
// remaining tokens when malformed JSON falls back to shell or list form.
SLASH_DOUBLE_QUOTE_CONTINUATION
    : '\\' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
SLASH_DOUBLE_QUOTE_END
    : '"' -> type(JSON_STRING_END), mode(SLASH_ARGS)
    ;
SLASH_DOUBLE_QUOTE_JSON_ESCAPE
    : JSON_ESCAPE_SEQUENCE -> type(JSON_STRING_ESCAPE)
    ;
SLASH_DOUBLE_QUOTE_JSON_SPACE: ' '+ -> type(JSON_STRING_SPACE);
SLASH_DOUBLE_QUOTE_LIST_WS: [\t\u000B\u000C]+ -> type(ARG_WS);
SLASH_DOUBLE_QUOTE_JSON_TEXT
    : ~["\\ \u0000-\u001F]+ -> type(JSON_STRING_TEXT)
    ;
SLASH_DOUBLE_QUOTE_ESCAPE: '\\' -> type(ESCAPE);
SLASH_DOUBLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(SLASH_BODY)
    ;
SLASH_DOUBLE_QUOTE_OTHER: . -> type(STRING_TEXT);

mode SLASH_SINGLE_QUOTE;

SLASH_SINGLE_QUOTE_CONTINUATION
    : '\\' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
SLASH_SINGLE_QUOTE_END
    : '\'' -> type(STRING_END), mode(SLASH_ARGS)
    ;
SLASH_SINGLE_QUOTE_WS: [ \t]+ -> type(ARG_WS);
SLASH_SINGLE_QUOTE_TEXT
    : ( ~['\\\r\n \t]+ | '\\' ~['\r\n \t] ) -> type(STRING_TEXT)
    ;
SLASH_SINGLE_QUOTE_ESCAPE: '\\' -> type(ESCAPE);
SLASH_SINGLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(SLASH_BODY)
    ;

mode BACKTICK_DOUBLE_QUOTE;

BACKTICK_DOUBLE_QUOTE_CONTINUATION
    : '`' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
BACKTICK_DOUBLE_QUOTE_END
    : '"' -> type(JSON_STRING_END), mode(BACKTICK_ARGS)
    ;
BACKTICK_DOUBLE_QUOTE_JSON_ESCAPE
    : JSON_ESCAPE_SEQUENCE -> type(JSON_STRING_ESCAPE)
    ;
BACKTICK_DOUBLE_QUOTE_JSON_SPACE: ' '+ -> type(JSON_STRING_SPACE);
BACKTICK_DOUBLE_QUOTE_LIST_WS: [\t\u000B\u000C]+ -> type(ARG_WS);
BACKTICK_DOUBLE_QUOTE_JSON_TEXT
    : ~["\\` \u0000-\u001F]+ -> type(JSON_STRING_TEXT)
    ;
BACKTICK_DOUBLE_QUOTE_JSON_BACKTICK: '`' -> type(JSON_STRING_TEXT);
BACKTICK_DOUBLE_QUOTE_BACKSLASH: '\\' -> type(STRING_TEXT);
BACKTICK_DOUBLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
BACKTICK_DOUBLE_QUOTE_OTHER: . -> type(STRING_TEXT);

mode BACKTICK_SINGLE_QUOTE;

BACKTICK_SINGLE_QUOTE_CONTINUATION
    : '`' [ \t]* NEWLINE CONTINUATION_IGNORED_LINE* -> skip
    ;
BACKTICK_SINGLE_QUOTE_END
    : '\'' -> type(STRING_END), mode(BACKTICK_ARGS)
    ;
BACKTICK_SINGLE_QUOTE_WS: [ \t]+ -> type(ARG_WS);
BACKTICK_SINGLE_QUOTE_TEXT
    : ( ~['`\r\n \t]+ | '`' ~['\r\n \t] ) -> type(STRING_TEXT)
    ;
BACKTICK_SINGLE_QUOTE_ESCAPE: '`' -> type(ESCAPE);
BACKTICK_SINGLE_QUOTE_NL
    : NEWLINE -> type(NL), mode(BACKTICK_BODY)
    ;
